# Generated by Django 5.2 on 2025-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='tiene_comprobante',
            field=models.BooleanField(default=False),
        ),
    ]
