# Generated by Django 5.2 on 2025-05-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcaje', '0002_permisos_tiene_comprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisocomprobante',
            old_name='Permiso',
            new_name='permiso',
        ),
    ]
